export const nodeMockHeader = [
  {
    id: "serviceName",
    disablePadding: true,
    label: "서비스명",
  },
  {
    id: "status",
    disablePadding: false,
    label: "상태",
  },
  {
    id: "nodeName",
    disablePadding: false,
    label: "노드명",
  },
  {
    id: "type",
    disablePadding: false,
    label: "유형",
  },
  {
    id: "serviceNameE",
    disablePadding: false,
    label: "서비스명",
  },
  {
    id: "IP",
    disablePadding: false,
    label: "IP",
  },
  {
    id: "newBlockNum",
    disablePadding: false,
    label: "최신블록번호",
  },
  {
    id: "newBlockTime",
    disablePadding: false,
    label: "최신블록시간",
  },
  {
    id: "TPS",
    disablePadding: false,
    label: "처리속도",
  },
  {
    id: "Latency",
    disablePadding: false,
    label: "지연율",
  },
];

export const nodeMockData = {
  nodeList: [
    {
      serviceName: "A서비스",
      status: "활성화",
      nodeName: "Node1",
      type: "Peer",
      serviceNameE: "Doc",
      IP: "http://www.xx1.",
      newBlockNum: "326849",
      newBlockTime: "2021-05-03",
      TPS: "250",
      Latency: "1.7",
    },
    {
      serviceName: "A서비스",
      status: "활성화",
      nodeName: "Node2",
      type: "Peer",
      serviceNameE: "Doc",
      IP: "http://www.xx2",
      newBlockNum: "326850",
      newBlockTime: "2021-05-03",
      TPS: "350",
      Latency: "1.7",
    },
    {
      serviceName: "A서비스",
      status: "활성화",
      nodeName: "Node3",
      type: "Peer",
      serviceNameE: "Doc",
      IP: "http://xxx.",
      newBlockNum: "326851",
      newBlockTime: "2021-05-03",
      TPS: "380",
      Latency: "1.9",
    },
    {
      serviceName: "A서비스",
      status: "활성화",
      nodeName: "Node4",
      type: "Peer",
      serviceNameE: "Doc",
      IP: "http://xxx.",
      newBlockNum: "326852",
      newBlockTime: "2021-05-03",
      TPS: "260",
      Latency: "1.7",
    },
    {
      serviceName: "B서비스",
      status: "활성화",
      nodeName: "Node5",
      type: "Peer",
      serviceNameE: "Doc",
      IP: "http://xxx.",
      newBlockNum: "326853",
      newBlockTime: "2021-05-03",
      TPS: "110",
      Latency: "4.2",
    },
    {
      serviceName: "B서비스",
      status: "활성화",
      nodeName: "Node6",
      type: "Peer",
      serviceNameE: "Doc",
      IP: "http://xxx.",
      newBlockNum: "326854",
      newBlockTime: "2021-05-03",
      TPS: "250",
      Latency: "1.7",
    },
    {
      serviceName: "B서비스",
      status: "활성화",
      nodeName: "Node7",
      type: "Peer",
      serviceNameE: "Doc",
      IP: "http://xxx.",
      newBlockNum: "326855",
      newBlockTime: "2021-05-03",
      TPS: "350",
      Latency: "1.7",
    },
    {
      serviceName: "C서비스",
      status: "활성화",
      nodeName: "Node8",
      type: "Peer",
      serviceNameE: "Doc",
      IP: "http://xxx.",
      newBlockNum: "326856",
      newBlockTime: "2021-05-03",
      TPS: "380",
      Latency: "1.9",
    },
    {
      serviceName: "C서비스",
      status: "활성화",
      nodeName: "Node9",
      type: "Peer",
      serviceNameE: "Doc",
      IP: "http://xxx.",
      newBlockNum: "326857",
      newBlockTime: "2021-05-03",
      TPS: "260",
      Latency: "1.7",
    },
    {
      serviceName: "C서비스",
      status: "활성화",
      nodeName: "Node10",
      type: "Peer",
      serviceNameE: "Doc",
      IP: "http://xxx.",
      newBlockNum: "326858",
      newBlockTime: "2021-05-03",
      TPS: "110",
      Latency: "4.2",
    },
  ],
};
